---
title: "Tasks automatisieren"
description: Ein Exkurs zu den Themen Funktionen und Loops.
date: "2023-03-13"
author:
  - name: Andrew Ellis
    url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0002-2788-936X
license: CC BY
citation: true
bibliography: ../../bibliography.bib
format:
    html:
        toc: true
        code-link: true
---

```{r}
#| include: false

# Set working directory of R
# knitr::opts_knit$set(root.dir = '../../data/rdk_decision_experiment')
```

:::{.callout-tip collapse="false"}
## Lernziele

In der heutigen Sitzung lernen wir:

- Funktionen erstellen
- Loops anwenden
:::



:::{.callout-caution collapse="true"}
## Datacamp
- Falls Sie eine Einführung in Programmierkonzepte (Conditionals and Control Flow, Functions, Loops) benötigen, empfehlen wir Ihnen den Datacamp Kurs [Intermediate R](https://app.datacamp.com/learn/courses/intermediate-r).
:::


# Funktionen

```{r}
add_one <- function(x) {
  x + 1
}
```


```{r}
add_one(2)
```

# Loops    



```{r}
names <- c("Socrates", "Nietzsche", "Kant", "Hume", "Plato")
```


```{r}
for (name in names) {
  print(paste("Hello", name))
}

```


```{r}
for (i in seq_along(names)) {
  print(paste("Hello", names[i]))
}
```

```{r}
lapply(names, function(x) paste("Hello", x))
```

```{r}
sapply(names, function(x) paste("Hello", x))
```


```{r}
library(tidyverse)
```

```{r}
names |> map(\(x) paste("Hello", x))
```

```{r}
say_hello <- function(x) {
  paste("Hello", x)
}
```

```{r}
names |> map(say_hello)
```

```{r}
names |> map(say_hello) |> unlist()
```

```{r
```

```{r}
```

```{r}