---
title: "Übung 5"
description: |
    Datenanalyse mit bayesianischem T-Test in JASP.
date: "2022-05-22"
author:
  - name: Andrew Ellis
    url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0002-2788-936X
  - name: Gerda Wyssen
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0001-7427-3149
license: CC BY
citation: true
bibliography: ../../bibliography.bib
format:
    html:
        toc: true
        code-link: true
execute: 
  cache: false
code-annotations: select
---

```{r}
#| include: false
# Set working directory of R
#knitr::opts_knit$set(root.dir = '../../data/uebung-5')
```


Die Übung 5 besteht aus den zwei folgenden Aufgaben:

**1. Datenanalyse in JASP**: Berechnen Sie in JASP mit einem T-Test, ob sich der Bias in Abhängigkeit vom Vorwissen verändert.

**2. Peer Feedback**: Geben Sie auf Ilias der Ihnen zugeordneten Person Rückmeldung zu ihrer Analyse und Einordnung einer anderen Person.


# 1. Datenanalyse in JASP

In dieser Übung nutzen wir unser Wissen über die Signalentdeckungstheorie sowie die bayesianische Statistik, um die Daten vom Entscheidungsexperiment, welches wir zu Beginn des Semsters durchgeführt haben, zu analysieren. 

Bei dem Random Dot Experiment wurde das Vorwissen der Person mit einem `cue` - einem nach rechts oder nach links zeigenden Pfeil - manipuliert. Einige Trials enthielten auch gar keinen Pfeil, diese werden wir hier nicht analysieren. Wir interessieren uns dafür, ob die Personen durch das gegebene Vorwissen tatsächlich beeinflusst in ihren Entscheidungen beeinflusst wurden. 

Als ein Mass für den Einfluss von Vorannahmen kann der "Bias" verwendet werden. Also wie stark eine Person dazu neigt, in eine bestimmte Richtung zu antworten. Mit Hilfe der Signalentdeckungstheorie haben wir [hier](https://kogpsy.github.io/neuroscicomplabFS23/pages/chapters/signal-detection-2.html) die Sensitivität (`dprime`), das Kriterium (`k`) und den Bias (`c`) für jede Person und Bedingung berechnet. 

:::{.callout-tip collapse="true"}
# Daten Vorverarbeitung

Die Daten entsprechen dem Datensatz [`sdt_final`](https://kogpsy.github.io/neuroscicomplabFS23/pages/chapters/signal-detection-2.html#mittelwerte-und-standardfehler), für die Analyse wurden die Daten ins `wide`-Format gebracht mit 

```
sdt_final_wide <- sdt_final |> 
    pivot_wider(names_from = cue, values_from = c(dprime, c, k))
``` 

und mit 

```write.csv(sdt_final_wide, "rdk_bayesian.csv", row.names = FALSE))```

abgespeichert. 
:::

Nun möchten wir testen, ob sich die Bedingungen "Pfeil zeigt nach rechts" und "Pfeil zeigt nach links" in Bezug auf den Bias (`c`) unterscheiden. Hierzu nutzen wir die Stärken eines bayesianischen T-Tests, wie  [hier](https://kogpsy.github.io/neuroscicomplabFS23/pages/chapters/bayesian-statistics-2.html) behandelt.

:::{.callout-important}
## Wichtig

👉 Laden Sie hier den Datensatz herunter: [RDK data für Übung 5](../../data/uebung-5/rdk_bayesian.csv).

👉 Für diese Übung benötigen Sie [JASP](https://jasp-stats.org/).
:::

Folgende Variablen sind im Datensatz `rdk_bayesian.csv`enthalten:

- `id`: Versuchspersonenidentifikation

- `dprime_none`, `dprime_right`, `dprime_left`: `dprime` für keinen Pfeil, einen Pfeil nach rechts, und einen Pfeil nach links

- `c_none`, `c_right`, `c_left`: Bias für jede Person und Bedingung

- `k_none`, `k_right`, `k_left`: Kriterium für jede Person und Bedingung


## Bayesianische Datenanalyse in JASP durchführen

Wir interessieren uns dafür, ob das Vorwissen den Bias der Versuchspersonen verschoben hat. Hat die Person aufgrund des Pfeils den sie gesehen hat, eher rechts oder links gedrückt?

Laden Sie den Datensatz in JASP und führen Sie einen Bayesianischen T-Test durch. Machen Sie sich Gedanken, welcher der drei auswählbaren T-Tests sich für unsere Daten am besten eignet.


## Ergebnisse berichten und interpretieren

Erstellen Sie ein Word oder Text-File, kopieren und beantworten Sie darin folgende Fragen:

1. Was waren die beiden Hypothesen, welche Sie getestet haben?

2. Berichten und Interpretieren der Ergebnisse:

- Welchen Test haben Sie verwendet?
- Wie gross ist der Unterschied zwischen den Bedingungen?
- Welche Bayes Factors haben Sie gefunden? Was bedeuten diese?
- Was bedeutet die eingefärbte "Torte"? 
- Haben Sie Evidenz für oder gegen eine Hypothese gefunden? 

3. Diskussion und Einordnung der Erkenntnisse:

- Die Studie, welche wir zum Vorbild genommen haben war eine fMRI Studie. Auf welche Areale könnten sich die gefundenen Resultate auswirken? 
- Gibt es wichtige Limitationen in der Interpretierbarkeit der Ergebnisse? 
- Was würden Sie ändern am Experiment, wenn Sie es noch einmal durchführen müssten?
- Welche Fragen bleiben offen?

Achten Sie darauf zu allen Punkten Antworten zu geben. 

# 2. Peer Feedback erstellen

## Fragen für Peer Feedback

Geben Sie im Textfeld auf Ilias der Ihnen zugeordneten Person kurz Feedback zu jedem Punkt. Das kann beispielsweise beinhalten, ob Sie auf dieselben Ergebnisse gekommen sind, oder ob Sie Ergänzungen haben.

Ihr Feedback sollte also mindestens (!!) 3 Rückmeldungspunkte umfassen.

## Peer Feedback hochladen

Laden Sie Ihr Peer Feedback anschliessend als Word/Text-File auf Ilias hoch.
