---
title: "Übung 1"
description: Daten erheben mit PsychoPy Experiment.
author:
  - name: Andrew Ellis
    url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0002-2788-936X
  - name: Gerda Wyssen
    # url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0001-7427-3149
license: CC BY
citation: true
bibliography: ../../bibliography_gw.bib
format:
    html:
        toc: true
---

In dieser Übung führen Sie mit zwei Personen das Random Dot Experiment durch und laden die Datensätze hoch. In dieser Übung gibt es kein *Peer Feedback*. Die erhobenen Daten werden wir dann in den kommenden Sitzungen verwenden. 

## Random Dot Experiment durchführen

- Das fertige Experiment befindet sich auf Github. Sie können es unter [diesem Link](https://github.com/kogpsy/psychopy-rdk-discrimination-task) downloaden. (Wenn Sie auf den grünen Button `Code` klicken, kann man das Experiment als Zip-Datei herunterladen: `Download ZIP`)

- Führen Sie das Experiment ein- oder mehrere Male selber durch. Kontrollieren Sie, ob ein Datensatz gespeichert wird.

- Testen Sie zwei Personen (Alter zwischen 20 und 60 Jahre). Diese Personen sollten die Hypothese nicht kennen (also keine Mitstudierende aus dem ComputerLab). 

## Datenabgabe

- Daten abgeben: Zippen Sie bitte die `.csv`-Datensätze der getesteten Personen (nicht von den Selbsttests) und __laden Sie das ZIP File bis in 10 Tagen auf ILIAS__.



## Trouble shooting

Bitte Fehlermeldung im Fenster genau durchlesen. Dort finden Sie Hinweise darauf, was schief gelaufen ist.

__Das Experiment startet nicht.__

- Unter `Einstellungen` (Radsymbol) den Reiter `Basic` auswählen. Bei `Use PsychoPy version` die laufende PsychoPy Version auswählen (z.B. `2022.2.5`).


__Das Experiment startet zwar, der Bildschirm ist aber dann einfach für eine kurze Zeit grau und das Fenster schliesst sich wieder.__

- Zugriffsrechte gegeben?

- Unter `Einstellungen` (Radsymbol) den Reiter `Input` auswählen. `Keyboard Backend` auf `PsychToolbox` statt `ioHub`.

