---
title: "Übung 2"
description: Datensätze einlesen und bearbeiten mit reproduzierbarem Code.
author:
  - name: Andrew Ellis
    url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0002-2788-936X
  - name: Gerda Wyssen
    # url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0001-7427-3149
license: CC BY
citation: true
bibliography: ../../bibliography_gw.bib
format:
    html:
        toc: true
---

Die Übung 2 besteht aus den zwei folgenden Aufgaben:

**1. Skript erstellen und ausführen**: In diesem Skript werden die Daten unseres PsychoPy-Experiments eingelesen, Variablen erstellt und erste Werte berechnet. Das Skript muss von einer anderen Person ausgeführt werden können (Reproduzierbarkeit) und gut kommentiert sein. Zeit: 1 Woche.

**2.  Peer Feedback**: Mittels Ilias wird Ihnen ein Skript einer anderen Person zugeordnet. Ihr Auftrag ist es, dieses Skript auszuführen und dazu Feedback zu geben. Zeit: 1 Woche.


# 1. Skript erstellen

## Vorbereitung

- Laden Sie zuerst das RStudio Projekt für Übung 2 herunter. Dieses muss "entzippt" werden. In dem Projektordner finden Sie den Ordner `data`. Darin befinden sich alle Datensätze des PsychoPy Experiments. Das Projekt kann durch einen Doppelklick auf das Projekt-File `uebung-2.Rproj` geöffnet werden.

:::{.callout-tip}
## Wichtig

👉 [RStudio Projekt für Übung 2 herunterladen](../../downloadable_files/uebung-2.zip)
:::

<aside>Projekte ermöglichen, *relative* Pfade. So stellen wir sicher, dass andere Personen, die dieses Projekt öffnen, dieses File auch sehen und ausführen können.</aside>

- Öffnen Sie das File `uebung-2_script.r`. Dieses File können Sie genau so verwenden und nach Bearbeitung speichern. Fügen Sie dem Filenamen Ihre Initialen an, das könnte dann so aussehen: `uebung-2_script_gw.r`. 

<aside>Praktischer ist es mit *RMarkdown* zu arbeiten. Das werden wir in den nächsten Wochen lernen. Dafür eignen sich z.B. `.qmd`-Files. Hier kann für Text die Markdown-Syntax verwendet werden, und der Code wird in Code-Blocks geschrieben.</aside>


## Kommentare & Code

- Kommentare werden mit `#`davor gekennzeichnet, so weiss `R`, dass dies Text und nicht ausführbarer Code ist. Verwenden Sie also vor jedem Kommentar am Anfang der Zeile ein `#`.

- Kommentieren Sie mit knappen, genauen Angaben. So weiss Ihr Peer Reviewer, was das Skript machen wird und was das Ziel des Codes ist.



## Aufgaben

- Gehen Sie das Skript durch. Das Skript enthält ein "Gerüst" an Code, mit dem Sie arbeiten können. Sie können auch den Code der Website übernehmen und etwas anpassen, wenn nötig. **Überall wo `___` steht, müssen Sie das Fehlende einfügen.** Manchmal ist das ein Kommentar. 
Manchmal ist es ein Codestück.

- Sie finden [hier](https://kogpsy.github.io/neuroscicomplabFS23/pages/chapters/importing_data-2.html) Infos dazu, wie die Daten bearbeitet werden können.


## Reproduzierbar machen

Sobald Sie den Code und die Kommentare ergänzt haben, ist es wichtig, das Skript auf seine Reproduzierbarkeit zu testen.

- Löschen Sie die Variablen im Workspace. Verwenden Sie dazu z.B. das "Besen"-Icon unter `Environment` oder nutzen Sie unter dem Reiter `Session` den Befehl `Clear Workspace`. Führen Sie __danach__ das Skript nochmals von oben bis unten aus.

- Prüfen Sie, ob alle Pfade relativ, also nicht an Ihren Rechner gebunden sind. 

- Prüfen Sie, ob alles gut und verständlich kommentiert ist.

- Prüfen Sie, ob Sie die 3 Werte für *Accuracy pro Bedingung* (für valide, invalide und neutral) als Kommentar in das Skript geschrieben haben.


## Hochladen

Laden Sie das `uebung-2_script_initialen.r` - Skript auf Ilias hoch.


# 2. Peer Feedback geben

## Vorbereitung

- Lesen Sie [hier](https://kogpsy.github.io/neuroscicomplabFS23/pages/admin/leistungsnachweise.html) die _Peer Feedback_-Grundsätze durch.

- Laden Sie das Ihnen zugeordnete `.r`-Skript herunter und speichern Sie es in Ihr R-Projektordner, wo sich auch das Projekt-File `uebung-2.Rproj` und Ihr eigenens `.r`-Skript befindet.

- Öffnen Sie das Projekt. Löschen Sie alle gespeicherten Variablen im Workspace. Verwenden Sie dazu z.B. das "Besen"-Icon unter `Environment` oder nutzen Sie unter dem Reiter `Session` den Befehl `Clear Workspace`. 


## Fragen für Peer Review

Öffnen Sie das `.r`-Skript und führen Sie es von oben bis unten aus und schreiben Sie zu folgenden Punkten eine Rückmeldung in ein Word/Text-File.

**1. Reproduzierbarkeit des Codes**

- Ist das Skript ausführbar? 

- Wenn nein: Wo genau gibt es eine Fehlermeldung, weshalb kommt diese und wie könnte diese behoben werden?

- Stimmen die 3 _Accuracy pro Bedingung_ - Werte mit den im Kommentar beschriebenen Werten überein?

- Stimmen die Werte mit den von Ihnen selber errechneten Werten überein?


**2. Kommentierung/Implementierung des Codes**
    
- Geben Sie mit mind. 5 Sätzen Rückmeldung zum `.r`-Skript. Mögliche Themen könnten z.B. sein: War der Code angemessen kommentiert? Was war gut? Was hätte man besser machen können? Sind Ihnen an den Daten ähnliche Dinge aufgefallen? Haben Sie etwas gelernt von dem gereviewten Skript? Oder haben Sie etwas besser gelöst gehabt in Ihrem Skript? Haben Sie Vorschläge? usw.


## Hochladen

Laden Sie Ihr Peer Review anschliessend als Word/Text-File auf Ilias hoch.
