---
title: "Syllabus"
# description: Inhalt des Kurses.
author:
  - name: Andrew Ellis
    url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0002-2788-936X
  - name: Gerda Wyssen
    # url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0001-7427-3149
license: CC BY
citation: false
# bibliography: ../../bibliography.bib
format:
    html:
        toc: true
---

# Sitzungen

An den 14 Sitzungen werden wir voraussichtlich diese Themen behandeln (kleine Änderungen vorbehalten).


### 1 Einführung

```Sitzung 1```

- Wir schauen uns ein paar in den Neurowissenschaften verwendeten Programmiersprachen (Python, R, Matlab) an, und diskutieren ChatGPT. 
- Einführung in DataCamp (für Python/R).


::: callout-important
Auf DataCamp den Python Einführungskurs ausprobieren.
:::



### 2 Experimente mit Python programmieren 
```Sitzungen 2 und 3```

- Wir erstellen selber ein Experiment mit `Python` und `PsychoPy`. 

### 3 Data Wrangling 
```Sitzungen 4 und 5```

- Wir schauen uns an, wie wir mit `R` die Daten aus unserem selber programmierten Experiment einlesen und bearbeiten können, um damit statistische Analysen durchzuführen.


### 4 Visualisieren 
```Sitzung 6```

- Explorative Datenanalyse und grafische Darstellung mit mit `R` package `ggplot2`.


### 5 Signal Detection Theory 
```Sitzungen 7 und 8```

- Wir verwenden ein in den Neurowissenschaften und der Psychologie beliebtes Modell für kategoriale oder ordinale Verhaltensdaten, um Daten aus unserem Experiment zu analysieren. 

### 6 Reaktionszeiten 
```Sitzungen 9 und 10```

- In diesen Sitzungen schauen wir uns Analysemethoden für Reaktionszeitdaten an.

### 7 Bayesianische Datenanalyse 
```Sitzungen 11, 12, 13, und 14```

- Im letzten Thema geht es um einen modernen Ansatz in der Statistik, welcher auf den Axiomen der Wahrscheinlichkeitstheorie beruht, und einige Vorteile gegenüber der herkömmlichen (frequentistischen) Statistik bietet. Wir werden hier mit dem Programm `Jasp` arbeiten.

